services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: herald-azurite
    environment:
      AZURITE_ACCOUNTS: "heraldstore:Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw=="
    ports:
      - "${AZURITE_BLOB_PORT:-10000}:10000"
      - "${AZURITE_QUEUE_PORT:-10001}:10001"
      - "${AZURITE_TABLE_PORT:-10002}:10002"
    volumes:
      - herald-azurite:/data
    command: "azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0"
    healthcheck:
      test: ["CMD", "nc", "-z", "127.0.0.1", "10000"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - herald

volumes:
  herald-azurite:

networks:
  herald:
    name: herald
    driver: bridge
